### ISSUE TITLE
How to find the TU

### ISSUE THREAD

**Issue by DMHe98** [shaorray/TT-seq_mESC_SL_2i_mTORi#1]
Hello, I read your article and script, they are very good work, but I still didn't really understand how you find TU, and I did not find how to use  "GenoSTAN ", please can you provide a detailed pipline on how to find TU?

**Comment by shaorray** [comment]
Hi, thanks for the question, TU annotation is wrapped in another repo:
https://github.com/shaorray/TU_filter

You could find the usage of `GenoSTAN` in this shiny app, from line [#1576](https://github.com/shaorray/TU_filter/blob/1ca769dfb6c66e3ab3197f79ba5cba2646503d41/app.R#L1576).
For more details about `GenoSTAN`, please check out its Bioconductor manual:
https://www.bioconductor.org/packages/release/bioc/vignettes/STAN/inst/doc/STAN-knitr.pdf

The statistical model behind is HMM (hidden Markov model), in common with a similar package called [`GroHMM`](https://www.bioconductor.org/packages/release/bioc/html/groHMM.html). I don't think these two packages have a big difference, and calling TU can also use [`HOMER`'s implementation](http://homer.ucsd.edu/homer/ngs/groseq/groseq.html). 

`TU filter` shiny app is graphical and takes >1 bam file + a gene reference file (gtf format), and outputs annotated TU in gff3 format. Probably it's easy to test, and a run usually takes <10 minutes depending on the number of bam files. 

Starting with HOMER's shattered TU intervals, `TU filter` also can assemble them on the loaded gene references and output to the same TU gff3 format. You could find this alternative way on the 2nd page of the shiny app.

/Rui

**Comment by DMHe98** [comment]
> Hi, thanks for the question, TU annotation is wrapped in another repo: https://github.com/shaorray/TU_filter
> 
> You could find the usage of `GenoSTAN` in this shiny app, from line [#1576](https://github.com/shaorray/TU_filter/blob/1ca769dfb6c66e3ab3197f79ba5cba2646503d41/app.R#L1576). For more details about `GenoSTAN`, please check out its Bioconductor manual: https://www.bioconductor.org/packages/release/bioc/vignettes/STAN/inst/doc/STAN-knitr.pdf
> 
> The statistical model behind is HMM (hidden Markov model), in common with a similar package called [`GroHMM`](https://www.bioconductor.org/packages/release/bioc/html/groHMM.html). I don't think these two packages have a big difference, and calling TU can also use [`HOMER`'s implementation](http://homer.ucsd.edu/homer/ngs/groseq/groseq.html).
> 
> `TU filter` shiny app is graphical and takes >1 bam file + a gene reference file (gtf format), and outputs annotated TU in gff3 format. Probably it's easy to test, and a run usually takes <10 minutes depending on the number of bam files.
> 
> Starting with HOMER's shattered TU intervals, `TU filter` also can assemble them on the loaded gene references and output to the same TU gff3 format. You could find this alternative way on the 2nd page of the shiny app.
> 
> /Rui

Okay, thanks for your reply, I will try again
